### ISSUE TITLE
Various fails during attempt to use `curator tag`

### ISSUE THREAD

**Issue by alanorth** [AlexAltea/curator#2]
I've tried with three different movie files, and curator crashes or fails in two different ways.

First:

```console
$ curator tag -s audio -t language --only-macrolanguages movie.mp4 
┌───┬──────┬────────┬─────────┬───┬─────────┐
│ # │ Name │ Stream │ Old tag │ → │ New tag │
├───┼──────┼────────┼─────────┼───┼─────────┤
└───┴──────┴────────┴─────────┴───┴─────────┘
Continue? [y/N]
```

Second:

```console
$ curator tag -s audio -t language --only-macrolanguages movie.mkv               
Traceback (most recent call last):
  File "/home/aorth/src/python-venvs/curator/bin/curator", line 8, in <module>
    sys.exit(main())
  File "/home/aorth/src/python-venvs/curator/lib/python3.10/site-packages/curator/cli.py", line 143, in main
    handler(sys.argv[2:])
  File "/home/aorth/src/python-venvs/curator/lib/python3.10/site-packages/curator/cli.py", line 119, in curator_tag
    plan = plan_tag(media, args.streams, args.tag, args.value, args.skip_tagged, opts)
  File "/home/aorth/src/python-venvs/curator/lib/python3.10/site-packages/curator/plans/tag.py", line 52, in plan_tag
    stream_value = stream_info['tags'].get(tag)
KeyError: 'tags
```

**Comment by AlexAltea** [comment]
First one actually succeeded, it just happens that the existing language tag matches the "guessed" language (by listening to the audio data).

Since no changes are needed, Curator drops the task from the plan so the table looks empty.

I'll add a status message for this kind of scenarios, something along the lines of `print("No files need to be updated.")`

**Comment by AlexAltea** [comment]
> ```
> $ curator tag -s audio -t language --only-macrolanguages movie.mkv               
> [...]
>   File "/home/aorth/src/python-venvs/curator/lib/python3.10/site-packages/curato r/plans/tag.py", line 52, in plan_tag
>     stream_value = stream_info['tags'].get(tag)
> KeyError: 'tags
> ```

That's really interesting, I didn't expect to find a file with a no `tags` blocks!

Can you share the output of `ffprobe -show_streams -of json movie.mkv`?

I'll just create an empty `tags: {}` dict if none exist.

**Comment by alanorth** [comment]
> Can you share the output of ffprobe -show_streams -of json movie.mkv?

Sure, here it is:

```json
{
    "streams": [
        {
            "index": 0,
            "codec_name": "h264",
            "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
            "profile": "High",
            "codec_type": "video",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "width": 1280,
            "height": 544,
            "coded_width": 1280,
            "coded_height": 544,
            "closed_captions": 0,
            "film_grain": 0,
            "has_b_frames": 2,
            "sample_aspect_ratio": "1:1",
            "display_aspect_ratio": "40:17",
            "pix_fmt": "yuv420p",
            "level": 40,
            "chroma_location": "left",
            "field_order": "progressive",
            "refs": 1,
            "is_avc": "true",
            "nal_length_size": "4",
            "r_frame_rate": "24000/1001",
            "avg_frame_rate": "24000/1001",
            "time_base": "1/1000",
            "start_pts": 0,
            "start_time": "0.000000",
            "bits_per_raw_sample": "8",
            "extradata_size": 42,
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0,
                "captions": 0,
                "descriptions": 0,
                "metadata": 0,
                "dependent": 0,
                "still_image": 0
            }
        },
        {
            "index": 1,
            "codec_name": "aac",
            "codec_long_name": "AAC (Advanced Audio Coding)",
            "profile": "LC",
            "codec_type": "audio",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "sample_fmt": "fltp",
            "sample_rate": "48000",
            "channels": 6,
            "channel_layout": "5.1",
            "bits_per_sample": 0,
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/1000",
            "start_pts": 0,
            "start_time": "0.000000",
            "extradata_size": 2,
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0,
                "captions": 0,
                "descriptions": 0,
                "metadata": 0,
                "dependent": 0,
                "still_image": 0
            }
        },
        {
            "index": 2,
            "codec_name": "subrip",
            "codec_long_name": "SubRip subtitle",
            "codec_type": "subtitle",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/1000",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 5949027,
            "duration": "5949.027000",
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0,
                "captions": 0,
                "descriptions": 0,
                "metadata": 0,
                "dependent": 0,
                "still_image": 0
            },
            "tags": {
                "language": "eng"
            }
        }
    ]
}
```

**Comment by AlexAltea** [comment]
Perfect, I'll be able to fix it. Give me few minutes.

**Comment by AlexAltea** [comment]
Fixed in https://github.com/AlexAltea/curator/commit/948fa816c0a5d0fc6bf1fcbe38b198ac5ab8f542.

**Comment by AlexAltea** [comment]
Added another related fix, make sure you update to 5d20bf3501fcd3daa4bd68d8597eb0fe58128328 just in case.

**Comment by alanorth** [comment]
Great the second case where the file was missing tags works much better now:

```console
$ curator tag -s audio -t language --only-macrolanguages movie.mkv                                   
┌───┬─────────────┬────────┬─────────┬───┬─────────┐
│ # │ Name        │ Stream │ Old tag │ → │ New tag │
├───┼─────────────┼────────┼─────────┼───┼─────────┤
│ 1 │ movie.mkv   │ 1      │ None    │ → │ eng     │
└───┴─────────────┴────────┴─────────┴───┴─────────┘
Continue? [y/N] 
```

But the first case with no changes is blank:

```console
$ curator tag -s audio -t language --only-macrolanguages movie.mp4
┌───┬──────┬────────┬─────────┬───┬─────────┐
│ # │ Name │ Stream │ Old tag │ → │ New tag │
├───┼──────┼────────┼─────────┼───┼─────────┤
└───┴──────┴────────┴─────────┴───┴─────────┘
```

**Comment by AlexAltea** [comment]
> But the first case with no changes is blank:

Forgot to add the warning, will do so tomorrow morning!

**Comment by AlexAltea** [comment]
Done.

**Comment by alanorth** [comment]
Works for me, thanks!

```console
$ curator tag -s audio -t language The\ K*m*
<< five minutes later :P >>
Current plan requires no tasks. There is nothing to be done.
```
