### ISSUE TITLE
Exception: Failed to extract audio sample

### ISSUE THREAD

**Issue by alanorth** [AlexAltea/curator#6]
Another class of failures I see sometimes:

```console
$ chrt -b 0 curator tag -s audio -t language --only-macrolanguages --log=DEBUG --max-audio-samples=20 Big\ Fish\ \(2003\).mkv 
2023-01-26 12:57:13,886 | INFO | Processing 1 input media files
2023-01-26 12:57:13,928 | DEBUG | Detecting audio language in stream #1 of media: "Big Fish (2003).mkv"
2023-01-26 12:57:16,421 | DEBUG | Sample #00: {'en': '0.4309', 'la': '0.2892', 'nn': '0.0427', 'zh': '0.0415', 'cy': '0.0330'}
2023-01-26 12:57:21,601 | DEBUG | Sample #01: {'en': '0.8818', 'nn': '0.0439', 'zh': '0.0120', 'haw': '0.0106', 'tr': '0.0069'}
2023-01-26 12:57:26,228 | DEBUG | Sample #02: {'en': '0.9936', 'nn': '0.0015', 'es': '0.0008', 'haw': '0.0005', 'ja': '0.0005'}
2023-01-26 12:57:31,725 | DEBUG | Sample #03: {'en': '0.9564', 'la': '0.0186', 'cy': '0.0105', 'nn': '0.0038', 'mi': '0.0022'}
2023-01-26 12:57:37,631 | DEBUG | Sample #04: {'en': '0.9635', 'nn': '0.0047', 'ja': '0.0035', 'zh': '0.0034', 'fr': '0.0022'}
2023-01-26 12:57:43,559 | DEBUG | Sample #05: {'en': '0.9949', 'pt': '0.0008', 'cy': '0.0005', 'nn': '0.0004', 'ja': '0.0004'}
2023-01-26 12:57:49,189 | DEBUG | Sample #06: {'en': '0.9664', 'nn': '0.0078', 'zh': '0.0028', 'ja': '0.0027', 'ms': '0.0025'}
2023-01-26 12:57:55,603 | DEBUG | Sample #07: {'en': '0.9975', 'la': '0.0005', 'pt': '0.0005', 'cy': '0.0003', 'haw': '0.0001'}
2023-01-26 12:58:02,348 | DEBUG | Sample #08: {'en': '0.9534', 'la': '0.0287', 'nl': '0.0026', 'fr': '0.0018', 'nn': '0.0017'}
2023-01-26 12:58:40,878 | DEBUG | Sample #09: {'en': '0.9756', 'ja': '0.0032', 'nn': '0.0024', 'pt': '0.0018', 'tr': '0.0014'}
2023-01-26 12:59:24,803 | DEBUG | Sample #10: {'en': '0.9892', 'la': '0.0026', 'pt': '0.0011', 'nn': '0.0010', 'ja': '0.0009'}
2023-01-26 13:00:12,647 | DEBUG | Sample #11: {'zh': '0.9326', 'en': '0.0311', 'nn': '0.0084', 'ru': '0.0028', 'fr': '0.0027'}
2023-01-26 13:01:04,385 | DEBUG | Sample #12: {'en': '0.9736', 'es': '0.0043', 'fr': '0.0027', 'pt': '0.0022', 'nn': '0.0019'}
2023-01-26 13:02:00,525 | DEBUG | Sample #13: {'en': '0.9553', 'cy': '0.0129', 'nn': '0.0118', 'la': '0.0028', 'zh': '0.0015'}
2023-01-26 13:03:01,597 | DEBUG | Sample #14: {'en': '0.9919', 'cy': '0.0015', 'nn': '0.0013', 'pt': '0.0009', 'la': '0.0009'}
2023-01-26 13:04:06,809 | DEBUG | Sample #15: {'en': '0.4640', 'la': '0.2123', 'zh': '0.0685', 'nn': '0.0555', 'jw': '0.0250'}
2023-01-26 13:05:15,847 | DEBUG | Sample #16: {'en': '0.9873', 'la': '0.0018', 'pt': '0.0014', 'cy': '0.0014', 'nn': '0.0012'}
2023-01-26 13:06:29,832 | DEBUG | Sample #17: {'en': '0.5325', 'la': '0.1774', 'nn': '0.0693', 'zh': '0.0597', 'ru': '0.0219'}
2023-01-26 13:07:48,453 | DEBUG | Sample #18: {'en': '0.9754', 'nn': '0.0039', 'zh': '0.0033', 'la': '0.0029', 'fr': '0.0020'}
2023-01-26 13:09:11,370 | DEBUG | Sample #19: {'en': '0.9610', 'la': '0.0130', 'zh': '0.0035', 'nn': '0.0030', 'fr': '0.0026'}
2023-01-26 13:09:11,380 | DEBUG | Detecting audio language in stream #2 of media: "Big Fish (2003).mkv"
Traceback (most recent call last):
  File "/home/aorth/src/python-venvs/curator/bin/curator", line 8, in <module>
    sys.exit(main())
  File "/home/aorth/src/python-venvs/curator/lib/python3.10/site-packages/curator/cli.py", line 168, in main
    handler(sys.argv[2:])
  File "/home/aorth/src/python-venvs/curator/lib/python3.10/site-packages/curator/cli.py", line 139, in curator_tag
    plan = plan_tag(media, args.streams, args.tag, args.value, args.skip_tagged, opts)
  File "/home/aorth/src/python-venvs/curator/lib/python3.10/site-packages/curator/plans/tag.py", line 63, in plan_tag
    lang = task.inputs[0].detect_language(opts)
  File "/home/aorth/src/python-venvs/curator/lib/python3.10/site-packages/curator/stream.py", line 73, in detect_language
    return self.detect_audio_language(opts)
  File "/home/aorth/src/python-venvs/curator/lib/python3.10/site-packages/curator/stream.py", line 107, in detect_audio_language
    raise Exception(f"Failed to extract audio sample from {self.media.path} with ffmpeg")
Exception: Failed to extract audio sample from Big Fish (2003).mkv with ffmpeg
```

Here are the streams:

```json
{
    "streams": [
        {
            "index": 0,
            "codec_name": "h264",
            "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
            "profile": "High",
            "codec_type": "video",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "width": 1920,
            "height": 1040,
            "coded_width": 1920,
            "coded_height": 1040,
            "closed_captions": 0,
            "film_grain": 0,
            "has_b_frames": 2,
            "sample_aspect_ratio": "1:1",
            "display_aspect_ratio": "24:13",
            "pix_fmt": "yuv420p",
            "level": 41,
            "chroma_location": "left",
            "field_order": "progressive",
            "refs": 1,
            "is_avc": "true",
            "nal_length_size": "4",
            "r_frame_rate": "27021/1127",
            "avg_frame_rate": "27021/1127",
            "time_base": "1/1000",
            "start_pts": 0,
            "start_time": "0.000000",
            "bits_per_raw_sample": "8",
            "extradata_size": 40,
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0,
                "captions": 0,
                "descriptions": 0,
                "metadata": 0,
                "dependent": 0,
                "still_image": 0
            },
            "tags": {
                "title": "x264 VBR @ 14500 Kbps"
            }
        },
        {
            "index": 1,
            "codec_name": "dts",
            "codec_long_name": "DCA (DTS Coherent Acoustics)",
            "profile": "DTS",
            "codec_type": "audio",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "sample_fmt": "fltp",
            "sample_rate": "48000",
            "channels": 6,
            "channel_layout": "5.1(side)",
            "bits_per_sample": 0,
            "initial_padding": 0,
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/1000",
            "start_pts": 0,
            "start_time": "0.000000",
            "bit_rate": "1536000",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0,
                "captions": 0,
                "descriptions": 0,
                "metadata": 0,
                "dependent": 0,
                "still_image": 0
            },
            "tags": {
                "language": "eng",
                "title": "English DTS 5.1 @ 1536 Kbps"
            }
        },
        {
            "index": 2,
            "codec_name": "vorbis",
            "codec_long_name": "Vorbis",
            "codec_type": "audio",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "sample_fmt": "fltp",
            "sample_rate": "48000",
            "channels": 2,
            "channel_layout": "stereo",
            "bits_per_sample": 0,
            "initial_padding": 0,
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/1000",
            "start_pts": 0,
            "start_time": "0.000000",
            "extradata_size": 3600,
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0,
                "captions": 0,
                "descriptions": 0,
                "metadata": 0,
                "dependent": 0,
                "still_image": 0
            },
            "tags": {
                "language": "eng",
                "title": "English Vorbis 2.0 @ 80 Kbps"
            }
        },
        {
            "index": 3,
            "codec_name": "subrip",
            "codec_long_name": "SubRip subtitle",
            "codec_type": "subtitle",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/1000",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 7509163,
            "duration": "7509.163000",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0,
                "captions": 0,
                "descriptions": 0,
                "metadata": 0,
                "dependent": 0,
                "still_image": 0
            },
            "tags": {
                "language": "eng",
                "title": "English"
            }
        },
        {
            "index": 4,
            "codec_name": "subrip",
            "codec_long_name": "SubRip subtitle",
            "codec_type": "subtitle",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/1000",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 7509163,
            "duration": "7509.163000",
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0,
                "captions": 0,
                "descriptions": 0,
                "metadata": 0,
                "dependent": 0,
                "still_image": 0
            },
            "tags": {
                "language": "chi",
                "title": "Chinese Simplified"
            }
        },
        {
            "index": 5,
            "codec_name": "subrip",
            "codec_long_name": "SubRip subtitle",
            "codec_type": "subtitle",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/1000",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 7509163,
            "duration": "7509.163000",
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0,
                "captions": 0,
                "descriptions": 0,
                "metadata": 0,
                "dependent": 0,
                "still_image": 0
            },
            "tags": {
                "language": "chi",
                "title": "Chinese Traditional"
            }
        },
        {
            "index": 6,
            "codec_name": "subrip",
            "codec_long_name": "SubRip subtitle",
            "codec_type": "subtitle",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/1000",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 7509163,
            "duration": "7509.163000",
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0,
                "captions": 0,
                "descriptions": 0,
                "metadata": 0,
                "dependent": 0,
                "still_image": 0
            },
            "tags": {
                "language": "fre",
                "title": "French"
            }
        },
        {
            "index": 7,
            "codec_name": "subrip",
            "codec_long_name": "SubRip subtitle",
            "codec_type": "subtitle",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/1000",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 7509163,
            "duration": "7509.163000",
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0,
                "captions": 0,
                "descriptions": 0,
                "metadata": 0,
                "dependent": 0,
                "still_image": 0
            },
            "tags": {
                "language": "gre",
                "title": "Greek"
            }
        },
        {
            "index": 8,
            "codec_name": "subrip",
            "codec_long_name": "SubRip subtitle",
            "codec_type": "subtitle",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/1000",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 7509163,
            "duration": "7509.163000",
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0,
                "captions": 0,
                "descriptions": 0,
                "metadata": 0,
                "dependent": 0,
                "still_image": 0
            },
            "tags": {
                "language": "pol",
                "title": "Polish"
            }
        },
        {
            "index": 9,
            "codec_name": "subrip",
            "codec_long_name": "SubRip subtitle",
            "codec_type": "subtitle",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/1000",
            "start_pts": 0,
            "start_time": "0.000000",
            "duration_ts": 7509163,
            "duration": "7509.163000",
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0,
                "captions": 0,
                "descriptions": 0,
                "metadata": 0,
                "dependent": 0,
                "still_image": 0
            },
            "tags": {
                "language": "swe",
                "title": "Swedish"
            }
        }
    ]
}
```

**Comment by AlexAltea** [comment]
Can you get me the output using https://github.com/AlexAltea/curator/commit/ed1158f3a6b1c43878bc01b80e7a097c00dfaa33?

Any ffmpeg/ffprobe errors will be displayed into stdout now.

**Comment by alanorth** [comment]
Currently getting a `ModuleNotFoundError`:

```console
...
  File "/home/aorth/src/python-venvs/curator/lib/python3.10/site-packages/curator/cli.py", line 10, in <module>
    from curator.databases import get_database
ModuleNotFoundError: No module named 'curator.databases'
```

I made sure to re-install deps from `requirements.txt` and reinstall the project with `pip install .`. Not sure if I need to do it differently...

**Comment by AlexAltea** [comment]
Sorry, [I'm an idiot](https://github.com/AlexAltea/curator/commit/d0e7f7d684d32015b1d307798802d5b2aa8b0f23). Try now!

**Comment by alanorth** [comment]
Awesome, it's this:

```console
[NULL @ 0x55a002c31000] Unable to find a suitable output format for '/tmp/tmpzhrhwn01/sample0000.vorbis'
/tmp/tmpzhrhwn01/sample0000.vorbis: Invalid argument
```

**Comment by AlexAltea** [comment]
@alanorth Should be fixed on https://github.com/AlexAltea/curator/commit/25d7a865e8a8013f05ee224e730a4f8ca79779e9

**Comment by alanorth** [comment]
Now I'm getting a different error:

```console
$ chrt -b 0 curator tag -s audio -t language --only-macrolanguages --log=DEBUG --max-audio-samples=1 Big\ Fish\ \(2003\).mkv
Exception: Failed to extract audio sample from Big Fish (2003).mkv with ffmpeg:
...
[NULL @ 0x55de71c101c0] Requested output format 'matroska,webm' is not a suitable output format
/tmp/tmp5_juh1a7/sample0000.matroska,webm: Invalid argument
```

The `Invalid argument` is similar to what I'm seeing now with the m4v file in https://github.com/AlexAltea/curator/issues/7#issuecomment-1406948654.

**Comment by AlexAltea** [comment]
Fixed with the latest commit.

(Apologies for the constant trial and error, it seems I don't have such a complete movie collection as yours 😄)

**Comment by AlexAltea** [comment]
Actually not quite... I see that's a format name with commas (I've never seen that!)

**Comment by AlexAltea** [comment]
Now it should work! 😅 

See https://github.com/AlexAltea/curator/commit/2893cd639581395c8cbeb81f349cd72465345036

**Comment by alanorth** [comment]
All good, thanks!

> Apologies for the constant trial and error, it seems I don't have such a complete movie collection as yours

LOL yes now it seems curator is much more robust compared to a few days ago. Bravo! Thanks for the quick response times and good work.
